document.write("<ul>");
document.write("<li id='menu'><a href='index.html'>home</a></li>");
document.write("<li id='menu'><a href='about.html'>about</a></li>");
document.write("<li class='uchikeshi' id='menu'><a href='comic.html'>comic</a></li>");
document.write("<li id='menu'><a href='gallery.html'>gallery</a></li>");
document.write("<li id='menu'><a href='howto.html'>how to</a></li>");
document.write("<li id='menu'><a href='diary.html'>diary</a></li>");
document.write("<li class='uchikeshi' id='menu'>profile</li>");
document.write("<li class='uchikeshi' id='menu'>links</li>");
document.write("<li class='uchikeshi' id='menu'>mail</li>");
document.write("</ul>");