document.write("<ul>");
document.write("<li><a href='../../../index.html'>home</a></li>");
document.write("<li><a href='../../../about.html'>about</a></li>");
document.write("<li><a href='../../../gallery.html'>gallery</a></li>");
document.write("<li class='uchikeshi'><a href='../../../howto.html'>how to</a></li>");
document.write("<li><a href='../../../diary.html'>diary</a></li>");
document.write("<li class='uchikeshi'>profile</li>");
document.write("<li class='uchikeshi'>links</li>");
document.write("<li class='uchikeshi'>mail</li>");
document.write("</ul>");